import express, { Request, Response, Router } from 'express';
import { ProviderParamType } from '@/game/types';
import { blingoService } from './blingo/service';

export const gameRouter: Router = (() => {
    const router = express.Router();
    router.post('/get_launcher_url', async (req: Request, res: Response) => {
        const launcher : ProviderParamType = req.body;
        const response = await blingoService.provideLauncher( launcher );
        res.json( response );
    });

    router.post('/currentGame', async (req: Request, res: Response) => {
        const response = {
            "config": {
                "stake": {
                    "amounts": [
                        0.1,
                        0.2,
                        0.5,
                        1,
                        2,
                        5,
                        10,
                        25,
                        50,
                        100
                    ],
                    "index": 2
                },
                "rows": 5,
                "columns": 5,
                "standardSpins": 10,
                "purchaseSpins": 40,
                "freePurchaseSpins": 5,
                "patterns": [
                    {
                        "index": 0,
                        "columns": 5,
                        "rows": 5,
                        "sequence": "1111100000000000000000000"
                    },
                    {
                        "index": 1,
                        "columns": 5,
                        "rows": 5,
                        "sequence": "0000011111000000000000000"
                    },
                    {
                        "index": 2,
                        "columns": 5,
                        "rows": 5,
                        "sequence": "0000000000111110000000000"
                    },
                    {
                        "index": 3,
                        "columns": 5,
                        "rows": 5,
                        "sequence": "0000000000000001111100000"
                    },
                    {
                        "index": 4,
                        "columns": 5,
                        "rows": 5,
                        "sequence": "0000000000000000000011111"
                    },
                    {
                        "index": 5,
                        "columns": 5,
                        "rows": 5,
                        "sequence": "1000010000100001000010000"
                    },
                    {
                        "index": 6,
                        "columns": 5,
                        "rows": 5,
                        "sequence": "0100001000010000100001000"
                    },
                    {
                        "index": 7,
                        "columns": 5,
                        "rows": 5,
                        "sequence": "0010000100001000010000100"
                    },
                    {
                        "index": 8,
                        "columns": 5,
                        "rows": 5,
                        "sequence": "0001000010000100001000010"
                    },
                    {
                        "index": 9,
                        "columns": 5,
                        "rows": 5,
                        "sequence": "0000100001000010000100001"
                    },
                    {
                        "index": 10,
                        "columns": 5,
                        "rows": 5,
                        "sequence": "1000001000001000001000001"
                    },
                    {
                        "index": 11,
                        "columns": 5,
                        "rows": 5,
                        "sequence": "0000100010001000100010000"
                    }
                ],
                "symbolPayouts": [
                    {
                        "id": "PURPLE_GEM",
                        "payouts": [
                            {
                                "symbols": 3,
                                "multiplier": 0.5
                            },
                            {
                                "symbols": 4,
                                "multiplier": 1
                            },
                            {
                                "symbols": 5,
                                "multiplier": 2.5
                            }
                        ]
                    }
                ],
                "patternPayouts": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                ],
                "instructions": {
                    "reelSymbols": [
                        "3",
                        "18",
                        "41",
                        "55",
                        "71"
                    ],
                    "jokerReelSymbols": [
                        "J",
                        "18",
                        "41",
                        "55",
                        "71"
                    ],
                    "ticket": {
                        "id": 0,
                        "rows": 5,
                        "columns": 5,
                        "cells": "12,19,37,47,74,14,18,38,50,75,1,19,32,55,71,6,28,35,50,66,7,22,39,57,67",
                        "matches": "0,0,1,1,1,0,1,1,1,0,0,1,1,1,1,0,1,1,0,0,1,1,1,1,1"
                    }
                },
                "winThreshold": 100,
                "spinDuration": 2.5
            },
            "bonusConfig": {
                "rows": 3,
                "columns": 5,
                "reels": [
                    {
                        "symbols": [
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "BAR",
                            "SEVEN",
                            "GREEN_GEM",
                            "BAR",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "BAR",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "BAR",
                            "ORANGE_GEM",
                            "BAR",
                            "BAR",
                            "SEVEN",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "SEVEN",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "BAR",
                            "BAR",
                            "SEVEN",
                            "BLUE_GEM",
                            "SEVEN",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "BAR",
                            "SEVEN",
                            "SEVEN",
                            "ORANGE_GEM",
                            "BAR",
                            "SEVEN",
                            "YELLOW_GEM",
                            "SEVEN",
                            "YELLOW_GEM",
                            "SEVEN",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "BAR",
                            "SEVEN",
                            "BAR",
                            "SEVEN",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "BAR",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "SEVEN",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "BAR",
                            "ORANGE_GEM",
                            "BAR",
                            "BAR",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "BAR",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "BAR",
                            "SEVEN",
                            "BAR",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "BAR",
                            "SEVEN",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "BAR",
                            "ORANGE_GEM",
                            "BAR",
                            "YELLOW_GEM",
                            "SEVEN",
                            "GREEN_GEM",
                            "BAR",
                            "BAR",
                            "SEVEN",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "SEVEN",
                            "GREEN_GEM",
                            "SEVEN",
                            "SEVEN",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "BAR",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "BAR",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "BAR",
                            "GREEN_GEM",
                            "SEVEN",
                            "BAR",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "SEVEN",
                            "SEVEN",
                            "BAR",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "BAR",
                            "YELLOW_GEM",
                            "SEVEN",
                            "YELLOW_GEM",
                            "BAR",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "SEVEN",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "SEVEN",
                            "BAR",
                            "BAR",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "ORANGE_GEM",
                            "SEVEN",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "SEVEN",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "BAR",
                            "BAR",
                            "ORANGE_GEM",
                            "SEVEN",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "BAR",
                            "ORANGE_GEM",
                            "SEVEN",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "BAR",
                            "BAR",
                            "ORANGE_GEM",
                            "BAR",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "SEVEN",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "BAR",
                            "ORANGE_GEM",
                            "SEVEN",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "BAR",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "SEVEN",
                            "BAR",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "SEVEN",
                            "SEVEN",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "SEVEN",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "SEVEN",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "SEVEN",
                            "YELLOW_GEM",
                            "SEVEN",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "ORANGE_GEM",
                            "BAR",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "SEVEN",
                            "YELLOW_GEM",
                            "BAR",
                            "SEVEN",
                            "SEVEN",
                            "SEVEN",
                            "ORANGE_GEM",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "SEVEN",
                            "YELLOW_GEM",
                            "BAR",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "SEVEN",
                            "BAR",
                            "BAR",
                            "SEVEN",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "BAR",
                            "SEVEN",
                            "ORANGE_GEM",
                            "BAR",
                            "BLUE_GEM",
                            "SEVEN",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "SEVEN",
                            "YELLOW_GEM",
                            "BAR",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "SEVEN"
                        ]
                    },
                    {
                        "symbols": [
                            "GREEN_GEM",
                            "SEVEN",
                            "BLUE_GEM",
                            "SEVEN",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "BAR",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "SEVEN",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "SEVEN",
                            "BAR",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "BAR",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "BAR",
                            "BAR",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "SEVEN",
                            "BAR",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "BAR",
                            "ORANGE_GEM",
                            "SEVEN",
                            "SEVEN",
                            "GREEN_GEM",
                            "SEVEN",
                            "GREEN_GEM",
                            "SEVEN",
                            "ORANGE_GEM",
                            "ORANGE_GEM",
                            "BAR",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "BAR",
                            "SEVEN",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "BAR",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "SEVEN",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "ORANGE_GEM",
                            "ORANGE_GEM",
                            "BAR",
                            "SEVEN",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "SEVEN",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "SEVEN",
                            "GREEN_GEM",
                            "SEVEN",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "BAR",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "SEVEN",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "SEVEN",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "ORANGE_GEM",
                            "SEVEN",
                            "ORANGE_GEM",
                            "ORANGE_GEM",
                            "SEVEN",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "BAR",
                            "BLUE_GEM",
                            "SEVEN",
                            "SEVEN",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "SEVEN",
                            "ORANGE_GEM",
                            "BAR",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "BAR",
                            "BLUE_GEM",
                            "SEVEN",
                            "BAR",
                            "SEVEN",
                            "SEVEN",
                            "ORANGE_GEM",
                            "BAR",
                            "BAR",
                            "ORANGE_GEM",
                            "BAR",
                            "YELLOW_GEM",
                            "SEVEN",
                            "BAR",
                            "SEVEN",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "BAR",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "SEVEN",
                            "SEVEN",
                            "SEVEN",
                            "BAR",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "BAR",
                            "BAR",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "SEVEN",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "SEVEN",
                            "ORANGE_GEM",
                            "BAR",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "BAR",
                            "GREEN_GEM",
                            "SEVEN",
                            "ORANGE_GEM",
                            "BAR",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "BAR",
                            "SEVEN",
                            "BAR",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "BAR",
                            "SEVEN",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "SEVEN",
                            "BLUE_GEM",
                            "SEVEN",
                            "BLUE_GEM",
                            "SEVEN",
                            "YELLOW_GEM",
                            "BAR",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "BAR",
                            "SEVEN",
                            "BAR",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "BAR",
                            "BLUE_GEM",
                            "SEVEN",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "SEVEN",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "BAR",
                            "BAR",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "SEVEN",
                            "ORANGE_GEM",
                            "BAR",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "BAR",
                            "BAR",
                            "BAR",
                            "GREEN_GEM",
                            "SEVEN",
                            "GREEN_GEM",
                            "SEVEN",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "SEVEN",
                            "ORANGE_GEM",
                            "SEVEN",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "ORANGE_GEM",
                            "SEVEN",
                            "YELLOW_GEM",
                            "BAR",
                            "BAR",
                            "YELLOW_GEM",
                            "SEVEN",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "ORANGE_GEM",
                            "BAR",
                            "SEVEN",
                            "BAR",
                            "GREEN_GEM",
                            "BAR",
                            "GREEN_GEM",
                            "BAR",
                            "EXPANDING_WILD",
                            "ORANGE_GEM",
                            "BAR",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "BAR",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "BAR",
                            "SEVEN",
                            "BAR",
                            "BLUE_GEM"
                        ]
                    },
                    {
                        "symbols": [
                            "YELLOW_GEM",
                            "BAR",
                            "SEVEN",
                            "SEVEN",
                            "SEVEN",
                            "BAR",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "SEVEN",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "SEVEN",
                            "SEVEN",
                            "SEVEN",
                            "SEVEN",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "SEVEN",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "BAR",
                            "BAR",
                            "SEVEN",
                            "BAR",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "SEVEN",
                            "SEVEN",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "BAR",
                            "ORANGE_GEM",
                            "BAR",
                            "BAR",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "BAR",
                            "GREEN_GEM",
                            "SEVEN",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "SEVEN",
                            "BAR",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "BAR",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "BAR",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "SEVEN",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "SEVEN",
                            "ORANGE_GEM",
                            "BAR",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "BAR",
                            "BLUE_GEM",
                            "SEVEN",
                            "ORANGE_GEM",
                            "BAR",
                            "BAR",
                            "ORANGE_GEM",
                            "ORANGE_GEM",
                            "BAR",
                            "BAR",
                            "BAR",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "SEVEN",
                            "SEVEN",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "SEVEN",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "BAR",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "BAR",
                            "SEVEN",
                            "ORANGE_GEM",
                            "SEVEN",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "SEVEN",
                            "ORANGE_GEM",
                            "BAR",
                            "ORANGE_GEM",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "BAR",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "ORANGE_GEM",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "BAR",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "SEVEN",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "SEVEN",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "SEVEN",
                            "ORANGE_GEM",
                            "BAR",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "BAR",
                            "ORANGE_GEM",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "BAR",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "SEVEN",
                            "YELLOW_GEM",
                            "BAR",
                            "ORANGE_GEM",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "SEVEN",
                            "GREEN_GEM",
                            "SEVEN",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "SEVEN",
                            "ORANGE_GEM",
                            "SEVEN",
                            "BLUE_GEM",
                            "SEVEN",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "BAR",
                            "ORANGE_GEM",
                            "SEVEN",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "BAR",
                            "SEVEN",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "SEVEN",
                            "GREEN_GEM",
                            "BAR",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "BAR",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "BAR",
                            "BLUE_GEM",
                            "SEVEN",
                            "SEVEN",
                            "YELLOW_GEM",
                            "SEVEN",
                            "SEVEN",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "SEVEN",
                            "BAR",
                            "BAR",
                            "SEVEN",
                            "SEVEN",
                            "BAR",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "BAR",
                            "SEVEN",
                            "ORANGE_GEM",
                            "SEVEN",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "BAR",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "BAR",
                            "ORANGE_GEM",
                            "EXPANDING_WILD",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "BAR",
                            "SEVEN",
                            "SEVEN",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "BAR",
                            "SEVEN",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "BAR",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "SEVEN",
                            "BAR",
                            "YELLOW_GEM",
                            "BAR",
                            "BAR",
                            "ORANGE_GEM",
                            "BAR",
                            "BAR",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "BAR",
                            "BAR",
                            "SEVEN",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "ORANGE_GEM",
                            "SEVEN",
                            "BAR",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "GREEN_GEM"
                        ]
                    },
                    {
                        "symbols": [
                            "BAR",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "BAR",
                            "SEVEN",
                            "ORANGE_GEM",
                            "SEVEN",
                            "YELLOW_GEM",
                            "SEVEN",
                            "YELLOW_GEM",
                            "BAR",
                            "SEVEN",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "SEVEN",
                            "YELLOW_GEM",
                            "SEVEN",
                            "BLUE_GEM",
                            "BAR",
                            "SEVEN",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "BAR",
                            "BAR",
                            "BAR",
                            "SEVEN",
                            "GREEN_GEM",
                            "SEVEN",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "BAR",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "ORANGE_GEM",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "BAR",
                            "SEVEN",
                            "SEVEN",
                            "GREEN_GEM",
                            "SEVEN",
                            "GREEN_GEM",
                            "SEVEN",
                            "SEVEN",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "SEVEN",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "BAR",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "BAR",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "SEVEN",
                            "SEVEN",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "SEVEN",
                            "BLUE_GEM",
                            "BAR",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "BAR",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "BAR",
                            "BAR",
                            "BAR",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "BAR",
                            "ORANGE_GEM",
                            "BAR",
                            "BAR",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "BAR",
                            "ORANGE_GEM",
                            "ORANGE_GEM",
                            "SEVEN",
                            "ORANGE_GEM",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "SEVEN",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "SEVEN",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "SEVEN",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "EXPANDING_WILD",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "SEVEN",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "SEVEN",
                            "SEVEN",
                            "SEVEN",
                            "BAR",
                            "BAR",
                            "SEVEN",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "SEVEN",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "SEVEN",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "SEVEN",
                            "BAR",
                            "BAR",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "BAR",
                            "BAR",
                            "BAR",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "BAR",
                            "ORANGE_GEM",
                            "BAR",
                            "ORANGE_GEM",
                            "BAR",
                            "BAR",
                            "BAR",
                            "BLUE_GEM",
                            "BAR",
                            "BAR",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "BAR",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "SEVEN",
                            "YELLOW_GEM",
                            "BAR",
                            "SEVEN",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "SEVEN",
                            "BAR",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "SEVEN",
                            "YELLOW_GEM",
                            "SEVEN",
                            "BAR",
                            "ORANGE_GEM",
                            "SEVEN",
                            "SEVEN",
                            "BAR",
                            "BAR",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "SEVEN",
                            "YELLOW_GEM",
                            "BAR",
                            "BLUE_GEM",
                            "SEVEN",
                            "ORANGE_GEM",
                            "SEVEN",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "SEVEN",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "ORANGE_GEM",
                            "SEVEN",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "ORANGE_GEM",
                            "BAR",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "BAR",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "SEVEN",
                            "GREEN_GEM",
                            "BAR",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "ORANGE_GEM",
                            "BAR",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "BAR",
                            "SEVEN",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "BAR",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "SEVEN",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "BAR",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "SEVEN",
                            "YELLOW_GEM",
                            "SEVEN",
                            "ORANGE_GEM",
                            "SEVEN",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "SEVEN",
                            "SEVEN",
                            "BAR",
                            "BAR",
                            "ORANGE_GEM"
                        ]
                    },
                    {
                        "symbols": [
                            "ORANGE_GEM",
                            "BAR",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "SEVEN",
                            "BAR",
                            "BAR",
                            "YELLOW_GEM",
                            "BAR",
                            "BAR",
                            "SEVEN",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "SEVEN",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "SEVEN",
                            "BAR",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "SEVEN",
                            "BAR",
                            "BLUE_GEM",
                            "SEVEN",
                            "SEVEN",
                            "GREEN_GEM",
                            "SEVEN",
                            "SEVEN",
                            "BAR",
                            "SEVEN",
                            "SEVEN",
                            "SEVEN",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "SEVEN",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "BAR",
                            "YELLOW_GEM",
                            "SEVEN",
                            "SEVEN",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "BAR",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "BAR",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "SEVEN",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "SEVEN",
                            "GREEN_GEM",
                            "SEVEN",
                            "ORANGE_GEM",
                            "BAR",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "BAR",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "SEVEN",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "SEVEN",
                            "BLUE_GEM",
                            "BAR",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "BAR",
                            "ORANGE_GEM",
                            "SEVEN",
                            "ORANGE_GEM",
                            "SEVEN",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "SEVEN",
                            "BAR",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "BAR",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "SEVEN",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "BAR",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "BAR",
                            "BAR",
                            "GREEN_GEM",
                            "SEVEN",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "BAR",
                            "BAR",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "BAR",
                            "BLUE_GEM",
                            "BAR",
                            "BLUE_GEM",
                            "SEVEN",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "BAR",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "BAR",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "SEVEN",
                            "ORANGE_GEM",
                            "SEVEN",
                            "ORANGE_GEM",
                            "BAR",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "BAR",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "SEVEN",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "SEVEN",
                            "SEVEN",
                            "GREEN_GEM",
                            "BAR",
                            "SEVEN",
                            "ORANGE_GEM",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "SEVEN",
                            "SEVEN",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "SEVEN",
                            "BAR",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "ORANGE_GEM",
                            "ORANGE_GEM",
                            "BAR",
                            "BAR",
                            "GREEN_GEM",
                            "BAR",
                            "YELLOW_GEM",
                            "BAR",
                            "BAR",
                            "ORANGE_GEM",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "ORANGE_GEM",
                            "ORANGE_GEM",
                            "YELLOW_GEM",
                            "BAR",
                            "BAR",
                            "YELLOW_GEM",
                            "BAR",
                            "SEVEN",
                            "BAR",
                            "ORANGE_GEM",
                            "BAR",
                            "SEVEN",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "BLUE_GEM",
                            "ORANGE_GEM",
                            "SEVEN",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "SEVEN",
                            "SEVEN",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "ORANGE_GEM",
                            "BLUE_GEM",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "GREEN_GEM",
                            "SEVEN",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "BLUE_GEM",
                            "SEVEN",
                            "SEVEN",
                            "BAR",
                            "BLUE_GEM",
                            "BAR",
                            "BLUE_GEM",
                            "BAR",
                            "BAR",
                            "GREEN_GEM",
                            "SEVEN",
                            "GREEN_GEM",
                            "SEVEN",
                            "SEVEN",
                            "ORANGE_GEM",
                            "BAR",
                            "BAR",
                            "SEVEN",
                            "BAR",
                            "BAR",
                            "ORANGE_GEM",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "GREEN_GEM",
                            "YELLOW_GEM",
                            "YELLOW_GEM",
                            "BAR",
                            "BLUE_GEM",
                            "YELLOW_GEM",
                            "BAR",
                            "SEVEN",
                            "BLUE_GEM",
                            "SEVEN",
                            "YELLOW_GEM",
                            "SEVEN",
                            "ORANGE_GEM"
                        ]
                    }
                ],
                "payouts": [
                    {
                        "id": "BLUE_GEM",
                        "payouts": [
                            {
                                "symbols": 3,
                                "multiplier": 5
                            },
                            {
                                "symbols": 4,
                                "multiplier": 10
                            },
                            {
                                "symbols": 5,
                                "multiplier": 25
                            }
                        ]
                    },
                    {
                        "id": "GREEN_GEM",
                        "payouts": [
                            {
                                "symbols": 3,
                                "multiplier": 8
                            },
                            {
                                "symbols": 4,
                                "multiplier": 20
                            },
                            {
                                "symbols": 5,
                                "multiplier": 50
                            }
                        ]
                    },
                    {
                        "id": "YELLOW_GEM",
                        "payouts": [
                            {
                                "symbols": 3,
                                "multiplier": 10
                            },
                            {
                                "symbols": 4,
                                "multiplier": 25
                            },
                            {
                                "symbols": 5,
                                "multiplier": 60
                            }
                        ]
                    },
                    {
                        "id": "BAR",
                        "payouts": [
                            {
                                "symbols": 3,
                                "multiplier": 50
                            },
                            {
                                "symbols": 4,
                                "multiplier": 200
                            },
                            {
                                "symbols": 5,
                                "multiplier": 250
                            }
                        ]
                    },
                    {
                        "id": "ORANGE_GEM",
                        "payouts": [
                            {
                                "symbols": 3,
                                "multiplier": 7
                            },
                            {
                                "symbols": 4,
                                "multiplier": 15
                            },
                            {
                                "symbols": 5,
                                "multiplier": 40
                            }
                        ]
                    },
                    {
                        "id": "SEVEN",
                        "payouts": [
                            {
                                "symbols": 3,
                                "multiplier": 25
                            },
                            {
                                "symbols": 4,
                                "multiplier": 60
                            },
                            {
                                "symbols": 5,
                                "multiplier": 120
                            }
                        ]
                    }
                ],
                "payLines": [
                    {
                        "id": 0,
                        "indexes": [
                            1,
                            1,
                            1,
                            1,
                            1
                        ]
                    },
                    {
                        "id": 1,
                        "indexes": [
                            0,
                            0,
                            0,
                            0,
                            0
                        ]
                    },
                    {
                        "id": 2,
                        "indexes": [
                            2,
                            2,
                            2,
                            2,
                            2
                        ]
                    },
                    {
                        "id": 3,
                        "indexes": [
                            0,
                            1,
                            2,
                            1,
                            0
                        ]
                    },
                    {
                        "id": 4,
                        "indexes": [
                            2,
                            1,
                            0,
                            1,
                            2
                        ]
                    },
                    {
                        "id": 5,
                        "indexes": [
                            0,
                            0,
                            1,
                            0,
                            0
                        ]
                    },
                    {
                        "id": 6,
                        "indexes": [
                            2,
                            2,
                            1,
                            2,
                            2
                        ]
                    },
                    {
                        "id": 7,
                        "indexes": [
                            1,
                            2,
                            2,
                            2,
                            1
                        ]
                    },
                    {
                        "id": 8,
                        "indexes": [
                            1,
                            0,
                            0,
                            0,
                            1
                        ]
                    },
                    {
                        "id": 9,
                        "indexes": [
                            1,
                            0,
                            1,
                            0,
                            1
                        ]
                    }
                ]
            },
            "wrapper": {},
            "balance": {
                "cash": 1000,
                "bonus": 0,
                "total": 1000,
                "currencyCode": "EUR"
            },
            "game": {
                "userId": 24177383,
                "ticket": {
                    "id": 342,
                    "rows": 5,
                    "columns": 5,
                    "cells": "11,22,35,56,73,8,27,34,49,68,4,20,31,51,62,5,19,32,48,61,15,24,40,55,66",
                    "matches": "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"
                },
                "state": "PURCHASE_ENTRY"
            },
            "response": 0
        };
        res.json( response );
    });

    router.post('/startGame', async (req: Request, res: Response) => {
        const actionParams  = {
            action : 1
        };
        blingoService.handleAction( actionParams );
        // res.send( response );
    });

    router.post('/spin', async (req: Request, res: Response) => {
        const actionParams  = {
            action : 2
        };
        blingoService.handleAction( actionParams );
    });

    router.post('/chooseCell', async (req: Request, res: Response) => {
        const actionParams  = {
            action : 3
        };
        blingoService.handleAction( actionParams );
    });

    router.post('/collect', async (req: Request, res: Response) => {
        const actionParams  = {
            action : 4
        };
        blingoService.handleAction( actionParams );
    });
    
    return router;
})();

export const configRouter : Router = (() => {
    const router = express.Router();
    router.get('/operators/gr-test/integrations/attributes', async( req:Request, res:Response ) => {
        const response = {
            "tablet": {
                "dialog_enabled": "true",
                "show_elapsed_time": "false",
                "help_button_enabled": "true",
                "reality_check_enabled": "true",
                "force_stop_enabled": "true",
                "reality_check_options_enabled": "true",
                "orientation_enabled": "true",
                "clock_enabled": "false",
                "show_net_position": "false",
                "you_could_win": "false",
                "cma_enabled": "true",
                "options_enabled": "true",
                "detailed_game_history_enabled": "false",
                "show_meta_bar": "false"
            },
            "all": {
                "controller": "GamingRealmsController",
                "buy_feature_enabled": "false",
                "user_autocomplete_enabled": "true",
                "user_autocomplete_expiry_hours": "24",
                "integration": "gamingrealms",
                "parameters": "OperatorParameters",
                "deploy": "games"
            },
            "phone": {
                "show_elapsed_time": "false",
                "help_button_enabled": "true",
                "reality_check_enabled": "true",
                "force_stop_enabled": "true",
                "reality_check_options_enabled": "true",
                "orientation_enabled": "true",
                "clock_enabled": "false",
                "show_net_position": "false",
                "you_could_win": "false",
                "cma_enabled": "true",
                "options_enabled": "true",
                "detailed_game_history_enabled": "false",
                "show_meta_bar": "false"
            }
        };
        res.send( response );
    });
    router.get('/games/client/slingo-starburst/attributes', async( req:Request, res:Response ) => {
        const response = {
            "name": "Slingo Starburst",
            "gameId": 1435,
            "externalGameId": "slingo-starburst",
            "clientAttributes": {
                "client_path": "rogue/starburst"
            }
        };

        res.send( response );
    });
    
    return router;
})();

export const cloudRouter : Router = (() => {
    const router = express.Router();

    router.post('/api/user/realityCheckDetails', async( req:Request, res:Response ) => {
        const response = {
            "realityCheckInterval": 0,
            "totalSessionTime": 0,
            "nextRealityCheck": 0,
            "rsp": 0
        };
        res.send( response );
    });
    return router;
})();

export const rgsRouter: Router = (() => {
    const router = express.Router();
    router.post('/user/login', async (req: Request, res: Response) => {
        const response = {
            "userId": 24177383,
            "username": "1732099498491",
            "st": "ACTIVE",
            "lastLoginDate": null,
            "timeZone": "America/New_York",
            "currentTime": 1732099500840,
            "access_token": "19492aed-7a6e-47b8-bd9f-27bef9ced775",
            "rn": "Slingo Starburst",
            "rsp": 0
        };
        res.send( response );
    });
    return router;
})();