export const ERRORDESCRIPTION : {[key: number]: string} = {
    0 : "Success",
    1 : "Insufficient balance.",
    2 : "Player not found or is logged out.",
    3 : "Bet is not allowed.",
    4 : "Player authentication failed due to invalid, not found or expired token.",
    5 : "Invalid hash code.",
    6 : "Player is frozen.",
    7 : "Bad parameters in the request, please check post parameters.",
    8 : "Game is not found or disabled.",
    9 : "Insufficient balance.",
    10 : "Bet limit has been reached.",
    11 : "Duplicated transaction.",
    12 : "Invalid transaction.",
    13 : "Bet/Round already started.",
    14 : "Transaction not found.",
    15 : "Bet/Round already closed",
    16 : "Round not found",
    20 : "Invalid user currency.",
    30 : "Provider not found",
    100 : "Internal server error.",
    120 : "Internal server error.",
    210 : "Reality check warning",
    310 : "Player's bet is out of his bet limits.",
    401 : "Unauthorized access",
}